name: Node.js CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Build Node.js app
        working-directory: ./react
        with:
          node-version: "14"
          cache: "npm"
        run: npm ci
        run: npm run build --if-present
